---
- name: Rodar pipelines do Kedro
  hosts: all
  vars:
    ansible_become: true
    ansible_become_method: sudo
    ansible_become_password: verderoot
    project_dir: /home/serverlab/stack-mine-track/mine-tracker
    venv_python: /home/serverlab/stack-mine-track/env/bin/python
    log_file: "{{ project_dir }}/info.log"

  tasks:
    - name: Verificar usuário atual
      shell: whoami
      become: true
      register: whoami_result

    - name: Exibir usuário
      debug:
        msg: "O comando está sendo executado como: {{ whoami_result.stdout }}"
      become: true

    - name: Verificar versão do Kedro no venv
      command: "{{ venv_python }} -m kedro --version"
      args:
        chdir: "{{ project_dir }}"
      register: kedro_version
      changed_when: false

    - name: Exibir versão do Kedro
      debug:
        msg: "Kedro versão: {{ kedro_version.stdout }}"

    - name: Rodar pipeline mine
      shell: |
        set -euo pipefail
        echo "==== $(date -Is) Pipeline: mine ====" | tee -a "{{ log_file }}"
        "{{ venv_python }}" -m kedro run --pipeline mine 2>&1 | tee -a "{{ log_file }}"
      args:
        chdir: "{{ project_dir }}"
        executable: /bin/bash

    - name: Rodar pipeline model
      shell: |
        set -euo pipefail
        echo "==== $(date -Is) Pipeline: model ====" | tee -a "{{ log_file }}"
        "{{ venv_python }}" -m kedro run --pipeline model 2>&1 | tee -a "{{ log_file }}"
      args:
        chdir: "{{ project_dir }}"
        executable: /bin/bash

    - name: Rodar pipeline inference
      shell: |
        set -euo pipefail
        echo "==== $(date -Is) Pipeline: inference ====" | tee -a "{{ log_file }}"
        "{{ venv_python }}" -m kedro run --pipeline inference 2>&1 | tee -a "{{ log_file }}"
      args:
        chdir: "{{ project_dir }}"
        executable: /bin/bash

